# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: run cucumber tests
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          sleep 60s
          echo "https://techcommunity.microsoft.com/t5/image/serverpage/image-id/73066i9A4C68E6EDEAEC11" >  cucumber-results-test-results.txt
      - name: Upload cucumber report
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: cucumber-results-test-results.txt
