# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: run cucumber tests
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "https://images.ctfassets.net/6afke33grie2/3eiey2skOlXAMWFJqwSN5r/9d49445b0b1da27f87d4e020a7cea320/deploy-logo.png" >  cucumber-results-test-results.txt
      - name: Upload cucumber report
        uses: actions/upload-artifact@v2
        with:
          name: Deploy
          path: cucumber-results-test-results.txt
