# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: run cucumber tests
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "<a href=\"https://s3-ap-southeast-2.amazonaws.com/gradfmir.assurity.co.nz/api/team1/test/cucumber-results-test-results.html\">Hi</a>" >  cucumber-results-test-results.html
      - name: Upload cucumber report
        uses: actions/upload-artifact@v2
        with:
          name: Test
          path: cucumber-results-test-results.html
